// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_U9oe6EpzV1qXYtalaZ0FDd4qCq1BNLY',
    appId: '1:725345062736:web:4e499e249a7c263ddde655',
    messagingSenderId: '725345062736',
    projectId: 'artfolio-14ad0',
    authDomain: 'artfolio-14ad0.firebaseapp.com',
    storageBucket: 'artfolio-14ad0.appspot.com',
    measurementId: 'G-B3LJ9RY9Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoizO66GnpMflczuvegAw-NV6gFJ3wYfw',
    appId: '1:725345062736:android:00b7539c8ba8edc4dde655',
    messagingSenderId: '725345062736',
    projectId: 'artfolio-14ad0',
    storageBucket: 'artfolio-14ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJyAN7kGAtJ0cQT0M3jqq36MhatblCQg',
    appId: '1:725345062736:ios:4cf4a147381caabbdde655',
    messagingSenderId: '725345062736',
    projectId: 'artfolio-14ad0',
    storageBucket: 'artfolio-14ad0.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJyAN7kGAtJ0cQT0M3jqq36MhatblCQg',
    appId: '1:725345062736:ios:fc4520c4d6ea0ccadde655',
    messagingSenderId: '725345062736',
    projectId: 'artfolio-14ad0',
    storageBucket: 'artfolio-14ad0.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
