// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKcI7r_iUPLCRzETLB7sLJ0mZ05Pc0tk',
    appId: '1:27003861059:web:36775e8b735b6bafeafcf6',
    messagingSenderId: '27003861059',
    projectId: 'p2art-1e1d3',
    authDomain: 'p2art-1e1d3.firebaseapp.com',
    storageBucket: 'p2art-1e1d3.appspot.com',
    measurementId: 'G-775XWVJMMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDemfPHH13Yfkb9q_l7mIwuDe4mu_Pjw',
    appId: '1:27003861059:android:df3dfe1626117a0aeafcf6',
    messagingSenderId: '27003861059',
    projectId: 'p2art-1e1d3',
    storageBucket: 'p2art-1e1d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3uOWgvYniviFe9VNUCDbJDAUxA6PQTHo',
    appId: '1:27003861059:ios:2aab7d2375d5d215eafcf6',
    messagingSenderId: '27003861059',
    projectId: 'p2art-1e1d3',
    storageBucket: 'p2art-1e1d3.appspot.com',
    iosBundleId: 'com.example.p2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3uOWgvYniviFe9VNUCDbJDAUxA6PQTHo',
    appId: '1:27003861059:ios:17e3c4114bcc310beafcf6',
    messagingSenderId: '27003861059',
    projectId: 'p2art-1e1d3',
    storageBucket: 'p2art-1e1d3.appspot.com',
    iosBundleId: 'com.example.p2.RunnerTests',
  );
}
